export const NEW = 'NEW',
  ADD_GENESIS = 'ADD_GENESIS',
  VALIDATE_BC = 'VALIDATE_BLOCKCHAIN',
  DISPLAY_ERROR = 'DISPLAY_ERROR',
  NEW_TRANSACTION = 'NEW_TRANSACTION',
  LATEST_BLOCKS = 'LATEST_BLOCKS'
