// flow-typed signature: bcd9c9e4d3f16ffb79e27d71c8780d10
// flow-typed version: <<STUB>>/@joj/adt_vfile:../adt/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@joj/adt'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@joj/adt' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@joj/adt/dist/box/index' {
  declare module.exports: any;
}

declare module '@joj/adt/dist/combinators/index' {
  declare module.exports: any;
}

declare module '@joj/adt/dist/conversions/index' {
  declare module.exports: any;
}

declare module '@joj/adt/dist/index' {
  declare module.exports: any;
}

declare module '@joj/adt/dist/maybe/index' {
  declare module.exports: any;
}

declare module '@joj/adt/dist/pair/index' {
  declare module.exports: any;
}

declare module '@joj/adt/dist/result/index' {
  declare module.exports: any;
}

declare module '@joj/adt/dist/validation/index' {
  declare module.exports: any;
}

declare module '@joj/adt/src/box/index' {
  declare module.exports: any;
}

declare module '@joj/adt/src/combinators/index' {
  declare module.exports: any;
}

declare module '@joj/adt/src/conversions/index' {
  declare module.exports: any;
}

declare module '@joj/adt/src/index' {
  declare module.exports: any;
}

declare module '@joj/adt/src/maybe/index' {
  declare module.exports: any;
}

declare module '@joj/adt/src/pair/index' {
  declare module.exports: any;
}

declare module '@joj/adt/src/result/index' {
  declare module.exports: any;
}

declare module '@joj/adt/src/validation/index' {
  declare module.exports: any;
}

declare module '@joj/adt/test/computeHash' {
  declare module.exports: any;
}

declare module '@joj/adt/test/ConversionsSpec' {
  declare module.exports: any;
}

declare module '@joj/adt/test/NaturalTransformSpec' {
  declare module.exports: any;
}

declare module '@joj/adt/test/PairSpec' {
  declare module.exports: any;
}

declare module '@joj/adt/test/ValidationFailureSpec' {
  declare module.exports: any;
}

declare module '@joj/adt/test/ValidationMaybeSpec' {
  declare module.exports: any;
}

declare module '@joj/adt/test/ValidationSpec' {
  declare module.exports: any;
}

declare module '@joj/adt/test/ValidationSuccessSpec' {
  declare module.exports: any;
}

// Filename aliases
declare module '@joj/adt/dist/box/index.js' {
  declare module.exports: $Exports<'@joj/adt/dist/box/index'>;
}
declare module '@joj/adt/dist/combinators/index.js' {
  declare module.exports: $Exports<'@joj/adt/dist/combinators/index'>;
}
declare module '@joj/adt/dist/conversions/index.js' {
  declare module.exports: $Exports<'@joj/adt/dist/conversions/index'>;
}
declare module '@joj/adt/dist/index.js' {
  declare module.exports: $Exports<'@joj/adt/dist/index'>;
}
declare module '@joj/adt/dist/maybe/index.js' {
  declare module.exports: $Exports<'@joj/adt/dist/maybe/index'>;
}
declare module '@joj/adt/dist/pair/index.js' {
  declare module.exports: $Exports<'@joj/adt/dist/pair/index'>;
}
declare module '@joj/adt/dist/result/index.js' {
  declare module.exports: $Exports<'@joj/adt/dist/result/index'>;
}
declare module '@joj/adt/dist/validation/index.js' {
  declare module.exports: $Exports<'@joj/adt/dist/validation/index'>;
}
declare module '@joj/adt/src/box/index.js' {
  declare module.exports: $Exports<'@joj/adt/src/box/index'>;
}
declare module '@joj/adt/src/combinators/index.js' {
  declare module.exports: $Exports<'@joj/adt/src/combinators/index'>;
}
declare module '@joj/adt/src/conversions/index.js' {
  declare module.exports: $Exports<'@joj/adt/src/conversions/index'>;
}
declare module '@joj/adt/src/index.js' {
  declare module.exports: $Exports<'@joj/adt/src/index'>;
}
declare module '@joj/adt/src/maybe/index.js' {
  declare module.exports: $Exports<'@joj/adt/src/maybe/index'>;
}
declare module '@joj/adt/src/pair/index.js' {
  declare module.exports: $Exports<'@joj/adt/src/pair/index'>;
}
declare module '@joj/adt/src/result/index.js' {
  declare module.exports: $Exports<'@joj/adt/src/result/index'>;
}
declare module '@joj/adt/src/validation/index.js' {
  declare module.exports: $Exports<'@joj/adt/src/validation/index'>;
}
declare module '@joj/adt/test/computeHash.js' {
  declare module.exports: $Exports<'@joj/adt/test/computeHash'>;
}
declare module '@joj/adt/test/ConversionsSpec.js' {
  declare module.exports: $Exports<'@joj/adt/test/ConversionsSpec'>;
}
declare module '@joj/adt/test/NaturalTransformSpec.js' {
  declare module.exports: $Exports<'@joj/adt/test/NaturalTransformSpec'>;
}
declare module '@joj/adt/test/PairSpec.js' {
  declare module.exports: $Exports<'@joj/adt/test/PairSpec'>;
}
declare module '@joj/adt/test/ValidationFailureSpec.js' {
  declare module.exports: $Exports<'@joj/adt/test/ValidationFailureSpec'>;
}
declare module '@joj/adt/test/ValidationMaybeSpec.js' {
  declare module.exports: $Exports<'@joj/adt/test/ValidationMaybeSpec'>;
}
declare module '@joj/adt/test/ValidationSpec.js' {
  declare module.exports: $Exports<'@joj/adt/test/ValidationSpec'>;
}
declare module '@joj/adt/test/ValidationSuccessSpec.js' {
  declare module.exports: $Exports<'@joj/adt/test/ValidationSuccessSpec'>;
}
